### ISSUE TITLE
Blank White Pages on Frontend

### ISSUE THREAD

**Issue by kevinorin** [dgt41/facebookfix#6]
ON Joomla 3.1.1 when enabled I get blank white pages on entire site.

**Comment by dgt41** [comment]
Joomla 3.1.1 is a little bit old, you should update to 3.4.4. I suspect that `$app->get('gzip')` this is the root of the problem as the syntax used to be `$app->getConfig('gzip')`. But just to make sure can you turn on the error reporting on the global configuration in order to see the actual error?

**Comment by dgt41** [comment]
Yes the syntax used here requires joomla >3.2 http://stackoverflow.com/questions/21702981/joomla-3-how-to-get-value-from-configuration-file

**Comment by kevinorin** [comment]
Thanks, I actually started upgrading Joomla and ran into issues with that.
I will complete the upgrade on my staging site and try the plugin again.

**Comment by dgt41** [comment]
you can replace this code:
```php
		if (($app->get('gzip') == 1) && $unsupported)
		{
			$app->set('gzip', 0);
		}
```
with:
```php
		if (($app->getConfig()->get('gzip') == 1) && $unsupported)
		{
			$app->getConfig()->set('gzip', 0);
		}
```
And should work with 3.1.1

**Comment by kevinorin** [comment]
I actually noticed Gzip compression is not on in Joomla admin...so the issue might be something else. The site is http://bit.ly/1Gcl0q3 and even though the logo shows up when I view source, when I shared on FB it shows only other images from the homepage and not the OG image.

You can resolve this issue.
